# Generated by Django 5.1.1 on 2024-09-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=100)),
                ('rec_desc', models.TextField()),
                ('rec_images', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
